---
abstract: 'Render and validate ExtJS forms using HTML::FormFu'
author:
  - 'Moritz Onken <onken@netcubed.de>'
generated_by: 'Dist::Zilla version 1.092680'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu-ExtJS
requires:
  Exporter: 5.57
  HTML::FormFu: 0.05001
  Hash::Flatten: 0
  Hash::Merge::Simple: 0.03
  JavaScript::Dumper: 0.011
  Tie::Hash::Indexed: 0
resources:
  repository: http://github.com/monken/html-formfu-extjs
version: 0.074
