---
abstract: 'Render and validate ExtJS forms using HTML::FormFu'
author:
  - '-2009 Moritz Onken, all rights reserved.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu-ExtJS
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Carp: 0
  Data::Dumper: 0
  Exporter: 5.57
  HTML::FormFu: 0.04
  Hash::Flatten: 0
  Hash::Merge::Simple: 0.03
  JavaScript::Dumper: 0.011
  Scalar::Util: 0
  Tie::Hash::Indexed: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.070
