---
abstract: 'Render and validate ExtJS forms using HTML::FormFu'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  DBIx::Class: 0
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  HTML::FormFu::Element::Text: 0
  Module::Build: 0.3601
  Test::More: 0.88
  overload: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 2.100960'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu-ExtJS
provides:
  HTML::FormFu::Element::ExtJS::Panel:
    file: lib/HTML/FormFu/Element/ExtJS/Panel.pm
    version: 0.076
  HTML::FormFu::Element::ExtJS::TabPanel:
    file: lib/HTML/FormFu/Element/ExtJS/TabPanel.pm
    version: 0.076
  HTML::FormFu::ExtJS:
    file: lib/HTML/FormFu/ExtJS.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Blank:
    file: lib/HTML/FormFu/ExtJS/Element/Blank.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Block:
    file: lib/HTML/FormFu/ExtJS/Element/Block.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Button:
    file: lib/HTML/FormFu/ExtJS/Element/Button.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Checkbox:
    file: lib/HTML/FormFu/ExtJS/Element/Checkbox.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Checkboxgroup:
    file: lib/HTML/FormFu/ExtJS/Element/Checkboxgroup.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::ComboBox:
    file: lib/HTML/FormFu/ExtJS/Element/ComboBox.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::ContentButton:
    file: lib/HTML/FormFu/ExtJS/Element/ContentButton.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Date:
    file: lib/HTML/FormFu/ExtJS/Element/Date.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::DateTime:
    file: lib/HTML/FormFu/ExtJS/Element/DateTime.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::ExtJS::Panel:
    file: lib/HTML/FormFu/ExtJS/Element/ExtJS/Panel.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::ExtJS::TabPanel:
    file: lib/HTML/FormFu/ExtJS/Element/ExtJS/TabPanel.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Fieldset:
    file: lib/HTML/FormFu/ExtJS/Element/Fieldset.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::File:
    file: lib/HTML/FormFu/ExtJS/Element/File.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Hidden:
    file: lib/HTML/FormFu/ExtJS/Element/Hidden.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Hr:
    file: lib/HTML/FormFu/ExtJS/Element/Hr.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Image:
    file: lib/HTML/FormFu/ExtJS/Element/Image.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Label:
    file: lib/HTML/FormFu/ExtJS/Element/Label.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Multi:
    file: lib/HTML/FormFu/ExtJS/Element/Multi.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Password:
    file: lib/HTML/FormFu/ExtJS/Element/Password.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Radio:
    file: lib/HTML/FormFu/ExtJS/Element/Radio.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Radiogroup:
    file: lib/HTML/FormFu/ExtJS/Element/Radiogroup.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Repeatable:
    file: lib/HTML/FormFu/ExtJS/Element/Repeatable.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Reset:
    file: lib/HTML/FormFu/ExtJS/Element/Reset.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Select:
    file: lib/HTML/FormFu/ExtJS/Element/Select.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::SimpleTable:
    file: lib/HTML/FormFu/ExtJS/Element/SimpleTable.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Src:
    file: lib/HTML/FormFu/ExtJS/Element/Src.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Submit:
    file: lib/HTML/FormFu/ExtJS/Element/Submit.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Text:
    file: lib/HTML/FormFu/ExtJS/Element/Text.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::Textarea:
    file: lib/HTML/FormFu/ExtJS/Element/Textarea.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::_Field:
    file: lib/HTML/FormFu/ExtJS/Element/_Field.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::_Group:
    file: lib/HTML/FormFu/ExtJS/Element/_Group.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::_MultiElement:
    file: lib/HTML/FormFu/ExtJS/Element/_MultiElement.pm
    version: 0.076
  HTML::FormFu::ExtJS::Element::_MultiSelect:
    file: lib/HTML/FormFu/ExtJS/Element/_MultiSelect.pm
    version: 0.076
  HTML::FormFu::ExtJS::Grid:
    file: lib/HTML/FormFu/ExtJS/Grid.pm
    version: 0.076
  HTML::FormFu::ExtJS::Util:
    file: lib/HTML/FormFu/ExtJS/Util.pm
    version: 0.076
recommends: {}
requires:
  Carp: 0
  Class::C3: 0
  Data::Dumper: 0
  Exporter: 0
  HTML::FormFu::Element::Block: 0
  HTML::FormFu::Util: 0
  Hash::Merge::Simple: 0
  JavaScript::Dumper: 0
  Scalar::Util: 0
  Tie::Hash::Indexed: 0
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=HTML-FormFu-ExtJS
  homepage: http://search.cpan.org/dist/HTML-FormFu-ExtJS/
  repository: http://github.com/monken/html-formfu-extjs
version: 0.076
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Filter/CompileTests'
      version: 1.100740
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Filter/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.100690
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Filter/MetaTests'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Filter/PortabilityTests'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@Filter/ReportVersions'
      version: 1.100880
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@Filter/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@Filter/AutoPrereq'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.100960
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.100701
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.100700
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.11
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.10001919
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git/Check'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git/Commit'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git/Tag'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git/Push'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 2.100960
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 2.100960
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 2.100960
